#!/bin/bash
echo "🌐 Port Forwarding Setup Helper"
echo "================================"

PUBLIC_IP=$(curl -4 -s ifconfig.me)
LOCAL_IP=$(hostname -I | awk '{print $1}')

echo "Your Network Details:"
echo "===================="
echo "Public IP: $PUBLIC_IP"
echo "Local IP: $LOCAL_IP"
echo "Router Gateway: 192.168.1.1"
echo ""
echo "📋 Router Configuration Steps:"
echo "=============================="
echo "1. Open browser and go to: http://192.168.1.1"
echo "2. Login with your router admin credentials"
echo "3. Look for: 'Port Forwarding' or 'Virtual Servers' or 'NAT' section"
echo "4. Add a new port forwarding rule:"
echo "   - Service Name: Inventory-App"
echo "   - External/WAN Port: 8080"
echo "   - Internal/LAN IP: $LOCAL_IP"
echo "   - Internal/LAN Port: 80"
echo "   - Protocol: TCP"
echo "5. Save the configuration"
echo "6. Restart your router (optional but recommended)"
echo ""
echo "🌐 After Setup - Access URLs:"
echo "============================"
echo "External Access: http://$PUBLIC_IP:8080"
echo "Local Access: http://$LOCAL_IP"
echo ""
echo "🧪 Test Commands:"
echo "================"
echo "Local Test: curl http://$LOCAL_IP/"
echo "External Test: curl http://$PUBLIC_IP:8080/ (after router config)"
echo ""
echo "⚠️  Security Notes:"
echo "=================="
echo "- Your app will be accessible from the internet"
echo "- Consider enabling firewall: sudo ufw enable"
echo "- Consider SSL/HTTPS for production use"
echo "- Monitor access logs: sudo tail -f /var/log/nginx/access.log"